title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        #### ⚠️ Don't forget to search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions) (including closed ones!).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you would like to see.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Add any other context or information about the feature request here.
